### ISSUE TITLE
Training Error. no attribute 'observation_space'

### ISSUE THREAD

**Issue by redcray** [NM512/dreamerv3-torch#11]
Thank you for your reproduction. I encountered this problem when trying to run atari training. Is my atari version incorrect? The version of gym installed is 0.19.0.

```
Traceback (most recent call last):
  File "/home/liangyb/git/dreamerv3-torch/dreamer.py", line 406, in <module>
    main(parser.parse_args(remaining))
  File "/home/liangyb/git/dreamerv3-torch/dreamer.py", line 353, in main
    train_envs[0].observation_space,
  File "/home/liangyb/git/dreamerv3-torch/envs/wrappers.py", line 177, in __getattr__
    return getattr(self._env, name)
  File "/home/liangyb/git/dreamerv3-torch/envs/wrappers.py", line 18, in __getattr__
    return getattr(self._env, name)
  File "/home/liangyb/git/dreamerv3-torch/envs/wrappers.py", line 203, in __getattr__
    return getattr(self._env, name)
  File "/home/liangyb/git/dreamerv3-torch/envs/wrappers.py", line 94, in __getattr__
    return getattr(self._env, name)
  File "/home/liangyb/git/dreamerv3-torch/envs/wrappers.py", line 143, in __getattr__
    return getattr(self._env, name)
AttributeError: 'Atari' object has no attribute 'observation_space' 
```

**Comment by redcray** [comment]
Thank you for your reply. The above problems have been solved, but there is still a problem.

```
Traceback (most recent call last):
  File "/home/liangyb/git/dreamerv3-torch/dreamer.py", line 406, in <module>
    main(parser.parse_args(remaining))
  File "/home/liangyb/git/dreamerv3-torch/dreamer.py", line 353, in main
    train_envs[0].observation_space,
  File "/home/liangyb/git/dreamerv3-torch/envs/wrappers.py", line 183, in observation_space
    spaces["reward"] = gym.spaces.Box(-np.inf, np.inf, dtype=np.float32)
  File "/home/liangyb/git/dreamerv3-torch/venv/lib/python3.10/site-packages/gym/spaces/box.py", line 49, in __init__
    raise ValueError(
ValueError: shape must be provided or inferred from the shapes of low or high
```

**Comment by NM512** [comment]
I apologize for the inconvenience. I inadvertently used gym==0.17.0, but I have now made modifications to the code so that it can also work with gym==0.19.0.
Thank you for your cooperation.

**Comment by redcray** [comment]
Thank you for your help. I have started training.
